In [13]:
import numpy as np
import pandas as pd

In [11]:
pip install sklearn.preprocessing

Collecting sklearn.preprocessing
  Downloading sklearn_preprocessing-0.1.0-py3-none-any.whl.metadata (70 bytes)
Downloading sklearn_preprocessing-0.1.0-py3-none-any.whl (10 kB)
Installing collected packages: sklearn.preprocessing
Successfully installed sklearn.preprocessing-0.1.0

In [12]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [53]:
df=pd.read_csv('/content/train.csv')

In [54]:
df.head()

,id,Brand,Material,Size,Compartments,Laptop Compartment,Waterproof,Style,Color,Weight Capacity (kg),Price
0,0,Jansport,Leather,Medium,7.0,Yes,No,Tote,Black,11.611723,112.15875
1,1,Jansport,Canvas,Small,10.0,Yes,Yes,Messenger,Green,27.078537,68.88056
2,2,Under Armour,Leather,Small,2.0,Yes,No,Messenger,Red,16.643760,39.17320
3,3,Nike,Nylon,Small,8.0,Yes,No,Messenger,Green,12.937220,80.60793
4,4,Adidas,Canvas,Medium,1.0,Yes,Yes,Messenger,Green,17.749338,86.02312

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 11 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   id                    300000 non-null  int64
 1   Brand                 290295 non-null  object
 2   Material              291653 non-null  object
 3   Size                  293405 non-null  object
 4   Compartments          300000 non-null  float64
 5   Laptop Compartment    292556 non-null  object
 6   Waterproof            292950 non-null  object
 7   Style                 292030 non-null  object
 8   Color                 290050 non-null  object
 9   Weight Capacity (kg)  299862 non-null  float64
 10  Price                 300000 non-null  float64
dtypes: float64(3), int64(1), object(7)
memory usage: 25.2+ MB

In [7]:
df.shape

(300000, 11)

In [8]:
df.shape

(26829, 11)

In [56]:
df.head(10)

,id,Brand,Material,Size,Compartments,Laptop Compartment,Waterproof,Style,Color,Weight Capacity (kg),Price
0,0,Jansport,Leather,Medium,7.0,Yes,No,Tote,Black,11.611723,112.15875
1,1,Jansport,Canvas,Small,10.0,Yes,Yes,Messenger,Green,27.078537,68.88056
2,2,Under Armour,Leather,Small,2.0,Yes,No,Messenger,Red,16.643760,39.17320
3,3,Nike,Nylon,Small,8.0,Yes,No,Messenger,Green,12.937220,80.60793
4,4,Adidas,Canvas,Medium,1.0,Yes,Yes,Messenger,Green,17.749338,86.02312
5,5,Nike,Canvas,Medium,10.0,No,Yes,NaN,Black,7.241812,20.01553
6,6,Nike,NaN,Large,3.0,No,No,Backpack,Green,6.828123,84.80500
7,7,Puma,Canvas,Small,1.0,Yes,Yes,Backpack,Blue,21.488864,27.15815
8,8,Under Armour,Polyester,Medium,8.0,Yes,No,Tote,Gray,10.207780,25.98652
9,9,Under Armour,Nylon,Medium,2.0,Yes,Yes,Messenger,Pink,15.895100,38.48741

Number of Null values in the attributes

In [57]:
#Sorting in ascending for the nul values
df.isnull().sum().sort_values()

id                         0
Compartments               0
Price                      0
Weight Capacity (kg)     138
Size                    6595
Waterproof              7050
Laptop Compartment      7444
Style                   7970
Material                8347
Brand                   9705
Color                   9950
dtype: int64

In [58]:
#Sorting for the unique values in descending order
df.nunique().sort_values()

Laptop Compartment           2
Waterproof                   2
Size                         3
Style                        3
Material                     4
Brand                        5
Color                        6
Compartments                10
Price                    48212
Weight Capacity (kg)    181596
id                      300000
dtype: int64

In [11]:
df.df['Color'].value_counts()

Color
Pink     4663
Gray     4539
Blue     4326
Black    4179
Red      4135
Green    4061
Name: count, dtype: int64

In [12]:
df['Waterproof'].value_counts()

Waterproof
Yes    13163
No     13033
Name: count, dtype: int64

In [13]:
df['Laptop Compartment'].value_counts()

Laptop Compartment
Yes    13361
No     12828
N          1
Name: count, dtype: int64

In [14]:
df['Style'].value_counts()

Style
Messenger    8920
Tote         8666
Backpack     8539
Name: count, dtype: int64

In [15]:
df['Material'].value_counts()

Material
Polyester    7247
Leather      6543
Nylon        6259
Canvas       6011
Name: count, dtype: int64

In [20]:

df.isnull().sum().sort_values()

id                         0
Compartments               0
Price                      0
Weight Capacity (kg)     138
Size                    6595
Waterproof              7050
Laptop Compartment      7444
Style                   7970
Material                8347
Brand                   9705
Color                   9950
dtype: int64

In [60]:
#Fill the na values
df['Weight Capacity (kg)']=df['Weight Capacity (kg)'].fillna(df['Weight Capacity (kg)'].mean())

df['Size']=df['Size'].fillna('Others')
df['Waterproof']=df['Waterproof'].fillna('Undetermined')
df['Laptop Compartment']=df['Laptop Compartment'].fillna('Undetermined')
df['Style']=df['Style'].fillna('Unknown')
df['Material']=df['Material'].fillna('others')
df['Brand']=df['Brand'].fillna('others')
df['Color']=df['Color'].fillna('others')

In [61]:
df.head()

,id,Brand,Material,Size,Compartments,Laptop Compartment,Waterproof,Style,Color,Weight Capacity (kg),Price
0,0,Jansport,Leather,Medium,7.0,Yes,No,Tote,Black,11.611723,112.15875
1,1,Jansport,Canvas,Small,10.0,Yes,Yes,Messenger,Green,27.078537,68.88056
2,2,Under Armour,Leather,Small,2.0,Yes,No,Messenger,Red,16.643760,39.17320
3,3,Nike,Nylon,Small,8.0,Yes,No,Messenger,Green,12.937220,80.60793
4,4,Adidas,Canvas,Medium,1.0,Yes,Yes,Messenger,Green,17.749338,86.02312

In [62]:
df.isnull().sum().sort_values()

id                      0
Brand                   0
Material                0
Size                    0
Compartments            0
Laptop Compartment      0
Waterproof              0
Style                   0
Color                   0
Weight Capacity (kg)    0
Price                   0
dtype: int64

In [63]:
type(df)

pandas.core.frame.DataFrame

In [19]:
x

,Brand,Material,Size,Compartments,Laptop Compartment,Waterproof,Style,Color,Weight Capacity (kg)
0,Jansport,Leather,Medium,7.0,Yes,No,Tote,Black,11.611723
1,Jansport,Canvas,Small,10.0,Yes,Yes,Messenger,Green,27.078537
2,Under Armour,Leather,Small,2.0,Yes,No,Messenger,Red,16.643760
3,Nike,Nylon,Small,8.0,Yes,No,Messenger,Green,12.937220
4,Adidas,Canvas,Medium,1.0,Yes,Yes,Messenger,Green,17.749338
...,...,...,...,...,...,...,...,...,...
26824,Nike,Polyester,Small,8.0,Yes,Yes,Backpack,Pink,14.984216
26825,Under Armour,Canvas,Medium,10.0,Yes,NaN,Tote,Gray,14.377528
26826,Under Armour,Nylon,Small,1.0,No,Yes,Backpack,Black,17.865984
26827,Puma,Nylon,Small,8.0,Yes,Yes,Tote,Black,25.567843
26828,Under Armour,Canvas,Medium,4.0,N,NaN,NaN,NaN,NaN

Handling missing values

In [64]:
from sklearn.model_selection import train_test_split
Target=df['Price']
x=df.drop(columns='Price')
y=Target

In [28]:
x.shape

(300000, 10)

In [29]:
y.shape

(300000,)

In [65]:
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2,random_state=41)

In [70]:
from sklearn.pipeline import make_pipeline
from tqdm import tqdm
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder
from sklearn.metrics import mean_squared_error

In [74]:
xgboost_params={'max_depth':8,
                'n_estimators':1701,
                'learning_rate':0.000678,
                'min_child_weight':0.275,
                'reg_alpha':0.527,
                'reg_lambda':13.91,
                'colsample_bylevel':0.977,
                'colsample_bytree':0.777,
                'colsample_bynode':0.8541
                }
lgd_params={'max_depth':17,
            'n_estimators':2771,
            'learning_rate':0.009,
            'min_child_weight':0.92,
            'reg_alpha':0.92,
            'reg_lambda':1.48,
            'colsample_bylevel':0.52,
            'colsample_bytree':0.99,
            'colsample_bynode':0.84}

algorithms=[LGBMRegressor(**lgd_params,verbose=-1,random_state=42),
            XGBRegressor(**xgboost_params,random_state=42)]

for algorithm in  tqdm(algorithms, desc='Starting'):
   model=make_pipeline(
      OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1),
      StandardScaler(),
      algorithm
  )
   alg_name=list(model.named_steps.keys())[-1]
#   alg_name = list(model.named_steps.keys())[-1]
   print(f"\nFitting the {alg_name}")
   model.fit(x_train,y_train)
   y_pred=model.predict(x_test)
   score=np.sqrt(mean_squared_error(y_test,y_pred))
   print(f"\nThe Score with the algorithm {alg_name} is {score}")

Starting:   0%|          | 0/2 [00:00<?, ?it/s]

Fitting the lgbmregressor

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
Starting:  50%|█████     | 1/2 [00:48<00:48, 48.39s/it]

The Score with the algorithm lgbmregressor is 39.42590110839692

Fitting the xgbregressor

Starting: 100%|██████████| 2/2 [01:38<00:00, 49.30s/it]

The Score with the algorithm xgbregressor is 39.06573859634714

In [96]:
df_test=pd.read_csv('/content/test.csv')

In [97]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 10 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   id                    200000 non-null  int64
 1   Brand                 193773 non-null  object
 2   Material              194387 non-null  object
 3   Size                  195619 non-null  object
 4   Compartments          200000 non-null  float64
 5   Laptop Compartment    195038 non-null  object
 6   Waterproof            195189 non-null  object
 7   Style                 194847 non-null  object
 8   Color                 193215 non-null  object
 9   Weight Capacity (kg)  199923 non-null  float64
dtypes: float64(2), int64(1), object(7)
memory usage: 15.3+ MB

In [98]:
df_test.isnull().sum().sort_values()

id                         0
Compartments               0
Weight Capacity (kg)      77
Size                    4381
Waterproof              4811
Laptop Compartment      4962
Style                   5153
Material                5613
Brand                   6227
Color                   6785
dtype: int64

In [99]:
df_test.head(10)

,id,Brand,Material,Size,Compartments,Laptop Compartment,Waterproof,Style,Color,Weight Capacity (kg)
0,300000,Puma,Leather,Small,2.0,No,No,Tote,Green,20.671147
1,300001,Nike,Canvas,Medium,7.0,No,Yes,Backpack,Green,13.564105
2,300002,Adidas,Canvas,Large,9.0,No,Yes,Messenger,Blue,11.809799
3,300003,Adidas,Nylon,Large,1.0,Yes,No,Messenger,Green,18.477036
4,300004,NaN,Nylon,Large,2.0,Yes,Yes,Tote,Black,9.907953
5,300005,Under Armour,Nylon,Medium,8.0,No,No,Backpack,Black,17.547673
6,300006,Nike,Nylon,Large,8.0,No,Yes,Tote,Blue,16.003025
7,300007,Jansport,Polyester,Medium,6.0,Yes,No,Backpack,Blue,24.238091
8,300008,Nike,Canvas,Large,8.0,Yes,Yes,Backpack,Red,19.181167
9,300009,Puma,Leather,Large,1.0,No,No,Tote,Blue,9.937962

In [100]:
df_test['Weight Capacity (kg)']=df['Weight Capacity (kg)'].fillna(df['Weight Capacity (kg)'].mean())
df_test['Size']=df_test['Size'].fillna('Other')
df_test['Material']=df_test['Material'].fillna('Other')
df_test['Waterproof']=df_test['Waterproof'].fillna('Undetermine')
df_test['Style']=df_test['Style'].fillna('Other')
df_test['Color']=df_test['Style'].fillna('Other')
df_test['Brand']=df['Brand'].fillna('Other')
df_test['Laptop Compartment']=df['Laptop Compartment'].fillna('Others')

In [101]:
df_test.isnull().sum().sort_values()

id                      0
Brand                   0
Material                0
Size                    0
Compartments            0
Laptop Compartment      0
Waterproof              0
Style                   0
Color                   0
Weight Capacity (kg)    0
dtype: int64

In [102]:
x_xtest=df_test

In [103]:
x_xtest.shape

(200000, 10)

In [104]:
y_xtest=model.predict(x_xtest)

In [107]:
pd.DataFrame({"Price":y_xtest}, index=df_test.index).to_csv(f'submission.csv')